-- ─────────────────────────────────────────────────────────────────────────────
-- 023_sed_documents.sql
-- Creates the sed_documents table and the sed-documents storage bucket.
-- (The task requested 017_ but 017_class_teacher_link.sql already exists —
--  this is numbered 023 as the next available slot.)
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── 1. Storage bucket ────────────────────────────────────────────────────
-- Private bucket — access only via signed URLs generated by the Edge Function.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'sed-documents',
  'sed-documents',
  FALSE,
  52428800,  -- 50 MB
  ARRAY['application/vnd.openxmlformats-officedocument.wordprocessingml.document']
)
ON CONFLICT (id) DO NOTHING;

-- School members can read objects in their own school's folder
DROP POLICY IF EXISTS "sed_objects_select" ON storage.objects;
CREATE POLICY "sed_objects_select" ON storage.objects
  FOR SELECT USING (
    bucket_id = 'sed-documents'
    AND EXISTS (
      SELECT 1 FROM school_members sm
      WHERE sm.user_id = auth.uid()
        AND sm.status = 'active'
        AND (storage.foldername(name))[1] = sm.school_id::text
    )
  );

-- ─── 2. sed_documents table ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS sed_documents (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id                   UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  academic_year               TEXT NOT NULL,
  file_path                   TEXT NOT NULL,
  generated_by                UUID REFERENCES profiles(id),
  generated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  overall_judgement_snapshot  INT CHECK (overall_judgement_snapshot BETWEEN 1 AND 5),
  file_size_bytes             BIGINT,
  UNIQUE (school_id, file_path)
);

ALTER TABLE sed_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sed_documents_school_access" ON sed_documents;
CREATE POLICY "sed_documents_school_access" ON sed_documents
  FOR SELECT USING (school_id = ANY(get_my_school_ids()));

-- INSERT is performed by the Edge Function using the service role key,
-- so no INSERT RLS policy is needed for regular users.
